# Generated by Django 6.0.6 on 2026-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='label',
            field=models.CharField(choices=[('Tumor', 'Tumor'), ('Lesion', 'Lesion'), ('Organ', 'Organ'), ('Background', 'Background')], default='Background', max_length=50),
        ),
    ]
